export type RoomKind = 'camp' | 'fight' | 'switches' | 'memory' | 'circuit' | 'timing' | 'treasure' | 'tool' | 'boss' | 'story' | 'rift';
export type Tool = 'bell' | 'hook' | 'lantern' | 'gust' | 'echo' | 'clock';
export interface Region { id: number; name: string; subtitle: string; color: string; ground: string; wall: string; water: string; tool: Tool; toolName: string; boss: string; keeper: string; intro: string[]; revelation: string; ending: string; rooms: string[]; letters: string[]; quest: string; questEnd: string }
export const regions: Region[] = [
  { id:1, name:'Der Briefwald', subtitle:'Was nie gesagt wurde, schlägt Wurzeln.', color:'#c3d889',ground:'#294a43',wall:'#163631',water:'#284a64',tool:'bell',toolName:'Traumglocke',boss:'Der unzuständige Hirsch',keeper:'Frau Falter',
    intro:['Du bist die neue Nachtpost? Gut. Die alte Nachtpost bin ich. Ich habe gerade Pause. Seit elf Jahren.','Die Bäume tragen Briefe, die niemand abzuschicken wagte. Seit der Morgen fehlt, wachsen sie uns über den Kopf.','Suche die Traumglocke am Glockenbaum. Sie zeigt die zweite Seite der Welt. Drei Poststempel öffnen den Weg zum Hirsch. Er behauptet, für nichts zuständig zu sein. Außer für alles.'],
    revelation:'Der erste Brief ist von Nox. Nicht von einem König. Von einem Vater: „Wenn ich die Nacht nur noch ein bisschen länger halten könnte.“',
    ending:'Der Hirsch faltet seine Dienstmütze zusammen. „Ich war übrigens immer zuständig. Ich hatte nur Angst, es falsch zu machen.“ Frau Falter reicht ihm einen winzigen Pausentee.',
    rooms:['Falterstation','Raschelweg','Glockenbaum','Die erste Lichtung','Papierfurt','Knotensteg','Echo im Grün','Postsortierung','Wurzelsaal','Die falsche Adresse','Drei Eichen','Faltwerkstatt','Mondlichtteich','Ungeöffnete Post','Wartezimmer im Moos','Hirschkanzlei'],
    letters:['Liebe Lio, ich wollte erst schreiben, wenn ich etwas Kluges sagen kann. Nun ist Winter. Also: Ich vermisse dich. Das muss reichen.','Sehr geehrter Baum, Ihre Blätter entsprechen keiner zugelassenen Papiergröße. Bitte wachsen Sie rechteckig. Mit freundlichen Grüßen, das Amt.','Ich habe den Weg nach Hause markiert. Nicht weil du dich verläufst. Sondern weil ich möchte, dass du weißt: Ich warte.','Dienstanweisung 3: Niemand ist zu klein, um eine wichtige Nachricht zu tragen. Dienstanweisung 4: Außer Ameisen. Die lesen alles.'],
    quest:'Finde die drei verlorenen Waldbriefe.',questEnd:'Frau Falter hängt eure gefundenen Briefe auf. Zum ersten Mal seit Jahren gibt es im Wald wieder Antworten.' },
  { id:2,name:'Das Uhrenviertel',subtitle:'Hier ist es immer fünf Minuten vor später.',color:'#efbe70',ground:'#4c4140',wall:'#2d2937',water:'#294866',tool:'hook',toolName:'Fadenhaken',boss:'Madame Minutenzeiger',keeper:'Oskar Ohnezeit',
    intro:['Meine Uhr geht nach. Um ungefähr einen Donnerstag.','Madame Minutenzeiger hat alle Termine eingesperrt, damit niemand zu spät kommen kann. Auch meinen Geburtstag. Ich war schon siebenmal fast vierzig.','Im Spulenhaus liegt der Fadenhaken. Er zieht euch zu goldenen Ankern und betäubt Gegner. Die Zahnräder hier hören noch auf Logik. Meistens.'],
    revelation:'Nox bat die Uhrmacherin nicht um mehr Macht. Er bat um eine weitere Stunde. Sie baute ihm eine Maschine, die keine Stunde wieder hergeben wollte.',
    ending:'Madame stoppt ihren Zeiger. „Ein Termin darf auch ausfallen?“ Oskar nickt. „Sogar meiner. Aber den Kuchen essen wir trotzdem.“',
    rooms:['Bahnhof Irgendwann','Pendelhöfe','Spulenhaus','Verspätungsgasse','Ziffernkanal','Ankerplatz','Drei vor Zwölf','Paketband','Zahnradgarten','Sekundenkeller','Der lange Dienstag','Uhrwerkraum','Mitternachtssteg','Brief an Gestern','Vorzimmer der Zeit','Madames Zifferblatt'],
    letters:['An mein jüngeres Ich: Du musst nicht alles schaffen. Vor allem nicht die Topfpflanze. Sie war schon vorher so.','Heute hat Nox gelächelt. Seine Tochter hat ihm eine Uhr gemalt, auf der jede Zahl „Jetzt“ heißt. Er trägt sie in der Tasche.','Der Zug nach Morgen entfällt. Ersatzverkehr: zu Fuß. Geschätzte Ankunft: wenn ihr da seid.','Oskar, wir feiern deinen Geburtstag, sobald du aufhörst, die Einladung zu korrigieren. Wir mögen dich auch ohne pünktliche Angaben.'],quest:'Sammle drei liegen gebliebene Einladungen.',questEnd:'Oskar lädt das ganze Viertel ein. Auf der Einladung steht nur: „Kommt, wenn ihr könnt.“ Es kommen alle.' },
  { id:3,name:'Die Laternenmoore',subtitle:'Nicht jedes Irrlicht will euch in die Irre führen.',color:'#a7d6d1',ground:'#273f4b',wall:'#1b293b',water:'#315b65',tool:'lantern',toolName:'Mutlaterne',boss:'Mutter Mumpf',keeper:'Irrlicht Else',
    intro:['Buh. Entschuldigung, berufliche Gewohnheit. Ich bin Else. Ich würde euch gern erschrecken, aber ich habe selbst Angst vor dem Nebel.','Mutter Mumpf sammelt hier alles, was man nicht fühlen möchte. Inzwischen passt sie kaum noch durch die Tür.','Nimm die Mutlaterne aus der alten Fähre. Ihr Licht löst Dornen und erreicht entfernte Kristalle. Dunkle Dinge sind selten so groß, wenn man sie ansieht.'],
    revelation:'In Nox’ Tagebuch steht keine Drohung. Nur eine durchgestrichene Zeile: „Was, wenn morgen anders wird?“ Darunter: „Dann soll morgen warten.“',
    ending:'Mumpf wird kleiner. Nicht weil ihre Sorgen verschwinden. Weil Else sich zu ihr setzt. Pipp bringt einen Stein. „Der hilft nicht. Aber er ist schön.“',
    rooms:['Elses Nebelsteg','Quakende Kurve','Alte Fähre','Schattenwiese','Schilfkanal','Lichtbrücke','Froschkonzert','Glühwürmchenpost','Versunkener Hof','Dornenkapelle','Die drei Flammen','Lampenwerk','Spiegelsumpf','Nasser Umschlag','Mumpfs Vorgarten','Das Haus im Nebel'],
    letters:['Liebe Sorge, ich habe dir ein Zimmer gegeben. Du hast das ganze Haus genommen. Wir müssen über die Miete reden.','Else, du bist kein schlechtes Irrlicht, nur weil du jemandem nach Hause geholfen hast. Vielleicht war die Stellenbeschreibung schlecht.','Froschorchester: Probe bei Mondaufgang. Bitte keine Fliegen während der stillen Stellen fangen. Wir hören das.','Mutter, ich komme am Sonntag. Du brauchst nichts aufzuräumen. Ich kenne uns.'],quest:'Finde drei tröstende Briefe im Moor.',questEnd:'Else liest die Briefe den Irrlichtern vor. Zum ersten Mal leuchten sie nicht, um jemanden zu locken, sondern um da zu sein.' },
  { id:4,name:'Die Wolkenküche',subtitle:'Liebe geht durch den Magen. Sturm leider auch.',color:'#f6c5a2',ground:'#675453',wall:'#40353e',water:'#7799a8',tool:'gust',toolName:'Windfächer',boss:'Chef Soufflé',keeper:'Tante Trude',
    intro:['Schuhe ab, Welt retten, Hände waschen. In dieser Reihenfolge.','Chef Soufflé will das perfekte Frühstück backen. Solange ein Krümel schief liegt, lässt er die Sonne nicht aufgehen.','Der Windfächer kühlt heiße Köpfe, pustet Gegner zurück und erreicht alle Schalter in der Nähe. Hol ihn aus dem Vorratsturm. Und bring keine Gewitter mit rein.'],
    revelation:'Die Maschine wurde mit einem Wunsch gestartet: „Möge dieser Abend niemals enden.“ Niemand hatte die Fußnote gelesen: Auch kein anderer Abend konnte nun beginnen.',
    ending:'Das Soufflé fällt zusammen. Alle halten den Atem an. Trude nimmt einen Löffel. „Schmeckt doch.“ Der Chef beginnt sehr leise zu lachen.',
    rooms:['Trudes Dachgarten','Mehlwindweg','Vorratsturm','Tassenallee','Milchstraße','Die kalte Platte','Kesselgesang','Frühstückspost','Krumme Croissants','Gewürzgewölbe','Drei Herdfeuer','Rezeptmaschine','Wolkenterrasse','Rezept für Zuhause','Das große Anrichten','Soufflés Ofen'],
    letters:['Zutaten für Zuhause: jemand kommt wieder. Jemand macht Platz. Salz nach Gefühl. Falls kein Gefühl da ist, erst einmal essen.','Chef, dein erstes Brot war schwarz und innen roh. Wir haben es trotzdem gegessen. Wir waren stolz. Nicht auf das Brot. Auf dich.','Das Amt beanstandet: Die Milchstraße enthält Spuren von Sternen. Kennzeichnungspflicht beachten.','Liebe Trude, dein Kuchenrezept fehlt im Archiv. Antwort: Gut. Dann müsst ihr zu Besuch kommen.'],quest:'Finde drei verschwundene Familienrezepte.',questEnd:'Trude klebt die Rezepte nicht an die Wand. Sie kocht sie. Ihr esst gemeinsam auf dem Dach, und niemand bewertet die Präsentation.' },
  { id:5,name:'Das Flüsterarchiv',subtitle:'Hier steht alles. Nur nie da, wo man sucht.',color:'#d0bae9',ground:'#433858',wall:'#28273e',water:'#415372',tool:'echo',toolName:'Echofeder',boss:'Der Korrektor',keeper:'Archivarin Ada',
    intro:['Psst. Die Bücher schlafen. Außer Band vier der Steuerordnung. Der tut nur so.','Der Korrektor entfernt alle Fehler aus den Erinnerungen. Leider auch Überraschungen, Witze und die meisten Menschen.','Die Echofeder sendet drei Funken statt einem. Im Archiv erreicht sie Schalter hinter Schatten. Dein eigenes Echo kann dich hier weiterbringen.'],
    revelation:'Lio ist nicht verschwunden. Sie ist erwachsen geworden und ausgezogen. Ihr letzter Brief liegt ungeöffnet in Nox’ Schreibtisch. Er fürchtete die Antwort mehr als die Ungewissheit.',
    ending:'„Unvollkommen“, sagt der Korrektor und betrachtet das offene Buch. Ada zieht einen Stuhl heran. „Deshalb lohnt sich die nächste Seite.“',
    rooms:['Adas Lesesaal','Flüstertreppe','Federkammer','Fußnotengang','Tintenkanal','Wortbrücke','Silbensaal','Sortierapparat','Die ungerade Seite','Durchgestrichen','Drei Randnotizen','Satzmaschine','Spiegelregister','Brief ohne Antwort','Letzte Korrektur','Der leere Absatz'],
    letters:['Hiermit widerrufe ich meine Behauptung, nichts bereut zu haben. Ich bereue den Haarschnitt von damals. Und dass ich mich nicht früher entschuldigt habe.','Papa, ich wohne jetzt am Meer. Hier riecht alles nach Salz und Möglichkeiten. Komm mich besuchen. Du musst kein Geschenk mitbringen. Nur dich. Lio.','Nutzungsordnung: Lachen ist im Lesesaal erlaubt, sofern das Buch wirklich gut ist. Bei sehr schlechten Büchern ebenfalls.','Lieber unbekannter Leser: Wenn du diesen Brief gefunden hast, war jemand neugierig genug. Ich hoffe, du bleibst es.'],quest:'Sammle drei zensierte Briefe.',questEnd:'Ada legt ein neues Regal an: „Dinge, die nicht perfekt sein müssen.“ Das Regal ist schief. Es passt hervorragend.' },
  { id:6,name:'Der Morgenpalast',subtitle:'Eine letzte Nacht. Ein erster Schritt.',color:'#f0d998',ground:'#394362',wall:'#252b49',water:'#506487',tool:'clock',toolName:'Sekundenherz',boss:'Die perfekte Wache',keeper:'Der müde Pförtner',
    intro:['Name? Mara. Anliegen? Morgen. Termin? Gestern. Sehr gut, ihr seid die Ersten, deren Papierkram hier Sinn ergibt.','Nox sitzt hinter der Morgenmaschine. Die perfekte Wache lässt nur hinein, wer keinen Fehler macht. Sie hat sich deshalb selbst eingeschlossen.','Das Sekundenherz im Turm verlangsamt Gegner. Die Zeit gehört nicht dem Amt. Sie gehört denen, die sie miteinander verbringen.'],
    revelation:'Pipp liest den Brief, den ihr die ganze Zeit getragen habt. Er ist von euch. „Lieber Morgen. Wir wissen nicht, was du bringst. Komm trotzdem.“',
    ending:'Die perfekte Wache lässt ihr Schild fallen. „Und wenn ich falsch entscheide?“ Mara reicht ihr die Hand. „Dann entscheiden wir danach noch einmal.“',
    rooms:['Pförtnerloge','Sternentreppe','Herzturm','Galerie der Dienste','Nachtkanal','Letzte Brücke','Der erste Ton','Ausgangspost','Saal der Möglichkeiten','Unterschriftenkeller','Drei offene Fenster','Morgenwerk','Himmelspiegel','Der letzte Brief','Vor der Entscheidung','Die perfekte Wache'],
    letters:['An alle Beschäftigten: Der Morgen ist kein genehmigungspflichtiger Vorgang. Dieser Aushang ersetzt alle anderslautenden Aushänge.','Nox, ich bin nicht böse, dass du Angst hattest. Ich bin traurig, dass du sie ganz allein getragen hast. Komm ans Meer. Wir haben zwei Stühle.','Pipp hat versucht, einen offiziellen Bericht zu schreiben. Er besteht aus einem Stern und einem sehr großen Ausrufezeichen. Der Bericht ist vollständig.','Wenn du nicht weißt, ob du bereit bist: Das ist kein Beweis dagegen. Pack eine Jacke ein. Geh los.'],quest:'Finde drei letzte Zustellungen.',questEnd:'Der Pförtner stempelt eure Briefe. „Zugestellt.“ Dann dreht er das Schild an seiner Tür um: „Bin draußen.“' },
];
export const toolInfo: Record<Tool,string> = {
  bell:'Wechselt zwischen Nacht und Traum. Geisterbrücken erscheinen, andere Hindernisse verschwinden. Der Wechsel funktioniert nur auf sicherem Boden.',
  hook:'Ein goldener Faden zieht dich zum nächsten Anker in Blickrichtung. Trifft er einen Gegner, wird dieser betäubt.',
  lantern:'Ein Lichtfunke löst Dornen und trifft Kristalle und Gegner. Im Traum glüht er besonders hell.',
  gust:'Ein Windstoß stößt Gegner zurück und aktiviert alle Kristalle in deiner Nähe.',
  echo:'Drei Federfunken fliegen fächerförmig. Sie treffen Gegner und Kristalle aus verschiedenen Richtungen.',
  clock:'Verlangsamt alle Gegner im Raum für vier Sekunden. Gut, wenn mehrere Dinge gleichzeitig dringend sind.',
};
export interface Skill { id:string; name:string; branch:string; cost:number; requires:string|null; description:string }
export const adventureSkills: Skill[] = [
  {id:'heart',name:'Ein großes Herz',branch:'Mut',cost:2,requires:null,description:'Zwei zusätzliche Herzen.'},
  {id:'edge',name:'Entschlossener Strich',branch:'Mut',cost:3,requires:'heart',description:'Nahkampf verursacht einen zusätzlichen Schaden.'},
  {id:'sweep',name:'Rundumschlag',branch:'Mut',cost:4,requires:'edge',description:'Dein Angriff erreicht auch Gegner hinter dir.'},
  {id:'resolve',name:'Noch nicht fertig',branch:'Mut',cost:5,requires:'sweep',description:'Bei höchstens zwei Herzen doppelter Nahkampfschaden.'},
  {id:'boots',name:'Leichte Schritte',branch:'Weg',cost:2,requires:null,description:'15 % schneller laufen.'},
  {id:'roll',name:'Aus dem Staub',branch:'Weg',cost:3,requires:'boots',description:'Rollen kostet weniger Ausdauer und lädt schneller nach.'},
  {id:'mend',name:'Durchatmen',branch:'Weg',cost:4,requires:'roll',description:'Jeder neu abgeschlossene Raum heilt ein Herz.'},
  {id:'pockets',name:'Gut vorbereitet',branch:'Weg',cost:5,requires:'mend',description:'Drei statt zwei Heiltees pro Rast.'},
  {id:'spark',name:'Sternenfunke',branch:'Stern',cost:2,requires:null,description:'Werkzeugtreffer verursachen einen zusätzlichen Schaden.'},
  {id:'flow',name:'Im Fluss',branch:'Stern',cost:3,requires:'spark',description:'Werkzeuge verbrauchen weniger Ausdauer.'},
  {id:'reach',name:'Weit gedacht',branch:'Stern',cost:4,requires:'flow',description:'Längere Betäubung und mehr Reichweite beim Windstoß.'},
  {id:'nova',name:'Kleiner Urknall',branch:'Stern',cost:5,requires:'reach',description:'Eine Ausweichrolle hinterlässt einen kleinen schädigenden Sternenkreis.'},
];
export const W=640,H=448,TILE=32;
export interface Room { id:string; region:number; index:number; name:string; kind:RoomKind; layout:number; exits:{direction:'n'|'s'|'e'|'w';to:string}[]; letter?:string; hint:string; required?:Tool }
const kinds:RoomKind[]=['camp','fight','tool','fight','switches','rift','memory','timing','fight','fight','switches','circuit','rift','story','fight','boss'];
const hints:Record<RoomKind,string>={camp:'Sprich mit dem Hüter. Am Lagerfeuer kannst du rasten und zurück ins Dorf reisen.',fight:'Besiege die Schatten. Achte auf ihre leuchtende Vorwarnung; rolle quer zum Angriff.',switches:'Finde und aktiviere die Kristalle in der auf der Stele genannten Reihenfolge. Ein Fehler setzt nur die Folge zurück.',memory:'Merke dir die Sternenfolge. Am Pult beginnt die Prüfung. Hinweise kosten keine Belohnung.',circuit:'Verbinde die beiden Leuchtpunkte. An der Werkbank kannst du die Leitungen drehen.',timing:'Sortiere die Nachtpost: tippe in der Mitte. Am Sortierer beginnt die Runde.',treasure:'Etwas Wertvolles wartet abseits des Wegs.',tool:'Öffne die große Truhe in der Mitte. Das Werkzeug gehört danach dauerhaft euch.',boss:'Drei Prüfungsstempel (Gedächtnis, Sortierung, Schaltkreis) öffnen die Bosskammer. Nutze Pausen nach Angriffen.',story:'Lies den Brief und sprich mit Pipp. Eure Entdeckungen bleiben im Reisebuch.',rift:'Benutze die Traumglocke, um unsichtbare Wege zu sehen. Wechsel nur auf sicherem Boden.'};
export const rooms:Room[]=[{id:'home',region:0,index:0,name:'Sternhafen',kind:'camp',layout:0,exits:[],hint:'Sprich mit Pipp am Brunnen. Die Reisekarte bringt euch zu den sechs Nachtpoststationen.'},...regions.flatMap(r=>r.rooms.map((name,index):Room=>{
 const x=index%4,y=Math.floor(index/4),exits:Room['exits']=[];
 if(x>0)exits.push({direction:'w',to:`${r.id}:${index-1}`});if(x<3)exits.push({direction:'e',to:`${r.id}:${index+1}`});
 if(y>0)exits.push({direction:'n',to:`${r.id}:${index-4}`});if(y<3)exits.push({direction:'s',to:`${r.id}:${index+4}`});
 return {id:`${r.id}:${index}`,region:r.id,index,name,kind:kinds[index],layout:(index+r.id)%6,exits,letter:[3,9,13,14].includes(index)?r.letters[[3,9,13,14].indexOf(index)]:undefined,hint:hints[kinds[index]],required:index===12?'bell':undefined};
})),{id:'final',region:6,index:16,name:'Die Morgenmaschine',kind:'story',layout:0,exits:[],hint:'Alle sechs Morgenlichter sind zurück. Sprich mit Nox.'}];
export const roomById=new Map(rooms.map(r=>[r.id,r]));
export function regionOpen(id:number,seals:readonly number[]) { return id<=1 || (id<=3?seals.includes(1):id<=5?seals.includes(2)&&seals.includes(3):seals.includes(4)&&seals.includes(5)); }
export function roomOpen(room:Room,cleared:readonly string[],tools:readonly string[]) {
 if(room.required&&!tools.includes(room.required))return false;
 return room.kind!=='boss'||(tools.includes(regions[room.region-1].tool)&&[6,7,11].every(i=>cleared.includes(`${room.region}:${i}`)));
}
export const opening=['Es ist 03:17 Uhr. Seit drei Tagen.','Mara ist Nachtpostbotin. Ihr letzter Auftrag war ein Paket mit der Aufschrift „Nicht schütteln“. Es hat zurückgeschüttelt.','Heute liegt ein Brief vor ihrer Tür. Absender: Morgen. Empfänger: Alle.','Pipp, ein vom Himmel gefallener Stern, hat eine Theorie: „Wenn morgen nicht kommt, müssen wir es eben abholen.“','Sechs Morgenlichter fehlen. Im Briefwald wartet Frau Falter auf jemanden, der klein genug für die Wurzeltüren und stur genug für das Amt ist. Zum Glück habt ihr beides.'];
export const finale=['Nox sitzt neben einer Maschine, die aussieht wie eine Uhr, ein Käfig und ein viel zu langer Arbeitstag.','„Ich wollte nur, dass ein guter Abend bleibt“, sagt er. „Lio war noch klein. Sie wollte die Sterne zählen. Wir kamen bis siebzehn.“','Mara legt Lios Brief auf den Tisch. „Sie zählt noch. Jetzt am Meer. Sie hat einen Stuhl für dich.“','Pipp berührt die Morgenmaschine. „Siebzehn ist keine schlechte Zahl. Aber achtzehn klingt auch schön.“','Nox sieht zum Fenster. Zum ersten Mal fragt er nicht, wie er den Morgen aufhalten kann. Er fragt, ob er zu spät ist.'];
