import './style.css';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { GameController } from '../index.ts';
import { adventureSkills,finale,opening,regions,regionOpen,rooms,roomById,toolInfo,W,H,type RoomKind,type Tool } from './content.ts';
import { availableSparks,buySkill,completeRoom,createWorld,enter,interact,maxHp,step,type World,type Save } from './model.ts';
import { circuit,circuitHint,circuitSolved,connected,rotate,seedNumber,sequence,timingPosition,type Circuit } from './puzzles.ts';
import { drawWorld } from './render.ts';
import { createAdventureAudio } from './audio.ts';
import { AdventureStorage,adventureApi,type AdventureApi } from './storage.ts';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
const symbols=['✦','☾','❧','◇'];
const names:Record<Tool,string>={bell:'Glocke',hook:'Fadenhaken',lantern:'Laterne',gust:'Windfächer',echo:'Echofeder',clock:'Sekundenherz'};
interface Options {container:HTMLElement;client:SupabaseClient;account:string;onExit():void;onArcade():void;api?:AdventureApi}
type Overlay='title'|'pause'|'map'|'skills'|'journal'|'dialogue'|'puzzle'|'conflict'|'ending'|null;
interface Puzzle {kind:RoomKind;time:number;stage:number;hits:number;index:number;phase:'preview'|'input'|'feedback';feedback:string;assist:boolean;sequence:number[];circuit:Circuit|null;lastVisual:number}
export function mountAdventure({container,client,account,onExit,onArcade,api=adventureApi(client)}:Options):GameController {
 let world:World|null=null,overlay:Overlay='title',resumeOverlay:Overlay=null,hidden=false,disposed=false,loaded=false,loadError='',frame=0,last=0,lastHud=0,saveTime=0;
 let toastUntil=0,dialogue:string[]=[],dialogueIndex=0,dialogueTitle='',afterDialogue:(()=>void)|null=null,puzzle:Puzzle|null=null;
 const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
 const keys=new Set<string>();let stick={x:0,y:0},pointer:number|null=null;const held={attack:false,roll:false,tool:false};let interaction=false;
 const audio=createAdventureAudio();
 const storage=new AdventureStorage(api,account,localStorage,()=>{if(disposed)return;updateSaveStatus();if(storage.conflict&&world){overlay='conflict';clearInput();renderPanel();audio.pause();}});
 container.className='nachtpost';
 container.innerHTML=`<div class="np-shell"><header class="np-header"><button data-np="exit" aria-label="Zum Logbuch">← Logbuch</button><strong>Nachtpost <span aria-hidden="true">✦</span></strong><button data-np="map">Karte</button><button data-np="pause">Pause</button></header><div class="np-hud"><div><span class="np-hearts" aria-label="Gesundheit"></span><div class="np-meter" aria-label="Ausdauer"><span></span></div></div><div class="np-location">Sternhafen</div><span class="np-save" role="status">Wird geladen …</span></div><div class="np-stage"><canvas width="${W}" height="${H}" aria-label="Nachtpost: Abenteuerwelt. Bewegung über Steuerfläche oder Pfeiltasten. Interaktion E." tabindex="0"></canvas><button class="np-quicktool" data-np="cycle" aria-label="Nächstes Werkzeug wählen" hidden>Werkzeug ↻</button><div class="np-bossbar" hidden></div><div class="np-toast" role="status" hidden></div></div><div class="np-controls"><div class="np-stick" role="group" aria-label="Bewegen: virtueller Joystick"><span class="np-stick-knob"></span></div><div class="np-actions"><button data-hold="attack">Schlag<small>J / Leertaste</small></button><button data-hold="roll">Rolle<small>K</small></button><button data-hold="tool" class="np-tool-button">Werkzeug<small>L</small></button><button data-np="interact">Aktion<small>E</small></button></div></div></div><section class="np-panel" aria-label="Spielmenü"><div class="np-panel-inner"></div></section>`;
 const canvas=container.querySelector('canvas')!,ctx=canvas.getContext('2d')!;
 const stage=container.querySelector<HTMLElement>('.np-stage')!;
 const resize=new ResizeObserver(()=>{const ratio=stage.clientWidth/Math.max(1,stage.clientHeight);canvas.width=Math.round(Math.min(W,H*ratio));canvas.height=Math.round(Math.min(H,W/ratio));});resize.observe(stage);
 const panel=container.querySelector<HTMLElement>('.np-panel')!,panelBody=container.querySelector<HTMLElement>('.np-panel-inner')!;
 const stickEl=container.querySelector<HTMLElement>('.np-stick')!,knob=container.querySelector<HTMLElement>('.np-stick-knob')!;
 function clearInput(){keys.clear();held.attack=held.roll=held.tool=false;interaction=false;stick={x:0,y:0};pointer=null;knob.style.transform='';}
 function notify(text:string){toastUntil=(world?.time??0)+7;const el=container.querySelector<HTMLElement>('.np-toast')!;el.textContent=text;el.hidden=false;}
 function updateSaveStatus(){const el=container.querySelector<HTMLElement>('.np-save');if(el){el.textContent=storage.conflict?'Speicherkonflikt':storage.error?'Speichern offen':storage.busy?'Speichert …':storage.pending?'Sicherung vorgemerkt':loaded?'Gespeichert':'Wird geladen …';el.title=storage.error;}}
 function checkpoint(){if(!world||!loaded||storage.conflict||disposed)return;storage.checkpoint(world.p);void storage.flush();}
 function pause(){if(!world||overlay==='title')return;if(storage.conflict){overlay='conflict';renderPanel();return;}if(['puzzle','dialogue','ending'].includes(overlay??''))resumeOverlay=overlay;else if(overlay===null)resumeOverlay=null;overlay='pause';clearInput();audio.pause();checkpoint();renderPanel();}
 function resume(){if(!world||storage.conflict)return;overlay=resumeOverlay;resumeOverlay=null;clearInput();if(overlay==='puzzle'&&puzzle){puzzle.time=0;if(puzzle.kind==='memory')puzzle.phase='preview';}last=performance.now();renderPanel();void audio.start(world.p.sound,world.room.region);}
 function openPanel(next:Overlay){clearInput();overlay=next;audio.pause();checkpoint();renderPanel();}
 function talk(title:string,lines:string[],after?:()=>void){clearInput();dialogueTitle=title;dialogue=lines;dialogueIndex=0;afterDialogue=after??null;overlay='dialogue';renderPanel();}
 function toolButtons(p:Save){return p.tools.map(t=>`<button data-equip="${t}" class="${p.equipped===t?'np-primary':''}">${names[t]}</button>`).join('');}
 function titleArt(){return `<svg class="np-title-art" viewBox="0 0 700 220" role="img" aria-label="Eine kleine Postbotin und ein Stern vor einem nächtlichen Dorf"><defs><linearGradient id="np-sky" x2="0" y2="1"><stop stop-color="#182d46"/><stop offset="1" stop-color="#537a75"/></linearGradient></defs><rect width="700" height="220" rx="18" fill="url(#np-sky)"/><circle cx="523" cy="62" r="30" fill="#e7d5a4"/><circle cx="536" cy="52" r="29" fill="#21384c"/><path d="M0 160Q100 100 210 159T410 146T700 160V220H0Z" fill="#254d4b"/><path d="M0 189Q160 153 320 184T700 175V220H0Z" fill="#193c3d"/><path d="M315 220L348 170L368 170L395 220" fill="#b0a782"/><g fill="#d8bd83"><path d="M108 114h56v66h-56zM550 125h44v56h-44z"/><path d="M90 115l46-40 47 40M537 127l35-32 36 32" fill="#536e73"/></g><g fill="#f5daa1"><path d="M121 142h13v16h-13zM146 142h10v16h-10zM564 145h12v15h-12z"/></g><ellipse cx="355" cy="190" rx="16" ry="5" fill="#0e2730"/><path d="M346 169l-8 24h35l-10-24" fill="#dcbe8f"/><circle cx="355" cy="163" r="9" fill="#e9cba9"/><path d="M344 157h22l-3-6h-15z" fill="#6baca8"/><path d="M384 139l3 8 8 3-8 3-3 8-3-8-8-3 8-3z" fill="#f6d894"/><g fill="#dac995"><circle cx="82" cy="40" r="1.5"/><circle cx="216" cy="55" r="2"/><circle cx="407" cy="33" r="1.5"/><circle cx="622" cy="74" r="2"/><circle cx="295" cy="87" r="1.5"/></g></svg>`;}
 function renderPanel(){
  panel.hidden=overlay===null;if(!overlay){panelBody.replaceChildren();return;}
  const p=world?.p;let body='';
  if(overlay==='title')body=`<span class="np-eyebrow">Ein Nachtpost-Abenteuer</span><h1>Das Amt für<br>verlorene Morgen</h1>${titleArt()}<p class="np-title-story">Der Morgen ist verschwunden. Das Amt sagt: alles in Ordnung. Eine Postbotin und ein kleiner Stern sehen das anders.</p>${loadError?`<p class="np-warning">${esc(loadError)}</p>`:''}<div class="np-panel-actions"><button class="np-primary" data-np="start" ${!loaded?'disabled':''}>${p?.intro?'Abenteuer fortsetzen':'Brief öffnen & aufbrechen'}</button><button data-np="arcade">Zur alten Spielstube</button></div><p class="np-muted">Ein gemeinsames Abenteuer. Euer Fortschritt wird gespeichert.<br>Touch: links bewegen, rechts handeln. Tastatur: WASD / Pfeile, J, K, L und E.<br>Die Spielstube bewahrt eure bisherigen XP und Fähigkeiten.</p>${loadError?'<button data-np="reload">Erneut laden</button>':''}`;
  else if(overlay==='conflict')body=`<span class="np-eyebrow">Euer gemeinsames Abenteuer</span><h2>Auf dem anderen Gerät ging es weiter.</h2><p>${esc(storage.error)}</p><p>Euer lokaler Stand bleibt als Sicherung erhalten. Ladet den gemeinsamen Stand, um dort weiterzuspielen. Er wird nicht automatisch mit diesem Gerät überschrieben.</p><div class="np-panel-actions"><button data-np="remote" class="np-primary">Gemeinsamen Stand laden</button><button data-np="export">Lokale Sicherung herunterladen</button></div>`;
  else if(!p)return;
  else if(overlay==='pause')body=`<span class="np-eyebrow">Die Welt kann kurz warten</span><h2>Eine kleine Verschnaufpause.</h2><p>${esc(world!.room.name)} · ${p.seals.length}/6 Morgenlichter · ${Math.floor(p.playSeconds/60)} Minuten unterwegs</p><div class="np-panel-actions"><button class="np-primary" data-np="resume">Weiterreisen</button><button data-np="skills">Fähigkeiten · ${availableSparks(p)} ✦</button><button data-np="journal">Reisebuch & Hinweise</button><button data-np="map">Karte & Schnellreise</button></div><h3>Euer Werkzeug</h3><div class="np-panel-actions">${toolButtons(p)||'<p>Das erste Werkzeug wartet am Glockenbaum im Briefwald.</p>'}</div><div class="np-panel-actions"><button data-np="sound">Musik: ${p.sound?'an':'aus'}</button><button data-np="difficulty">${p.difficulty==='cozy'?'Gemütlich':'Abenteuer'} · wechseln</button><button data-np="tea" ${p.tea<=0?'disabled':''}>Heiltee trinken · ${p.tea}</button><button data-np="save">Jetzt speichern</button><button data-np="retreat">Zur Poststation · Raum verlassen</button><button data-np="export">Spielstand exportieren</button><button data-np="export-conflict">Letzte Konfliktsicherung</button><button data-np="arcade">Spielstube</button></div>${storage.error?`<p class="np-warning">${esc(storage.error)}</p>`:''}<p class="np-muted">Gemütlich: Gegner handeln langsamer, längere Schutzzeit nach Treffern. Gleiche Geschichte und Belohnungen. Niederlagen kosten keine Entdeckungen.</p>`;
  else if(overlay==='skills')body=`<span class="np-eyebrow">Wachsen auf eure Art</span><h2>Was euch weiterbringt.</h2><p>${availableSparks(p)} Sternenfunken verfügbar. Räume, Briefe und Aufträge geben neue Funken.</p><div class="np-skills">${['Mut','Weg','Stern'].map(branch=>`<section><h3>${branch}</h3>${adventureSkills.filter(s=>s.branch===branch).map(s=>{const own=p.skills.includes(s.id),can=!own&&availableSparks(p)>=s.cost&&(!s.requires||p.skills.includes(s.requires));return `<article class="np-skill ${own?'owned':''}"><h3>${s.name}</h3><p>${s.description}</p><button data-skill="${s.id}" ${!can?'disabled':''}>${own?'✓ Entdeckt':`${s.cost} ✦ · Lernen`}</button></article>`;}).join('')}</section>`).join('')}</div><div class="np-panel-actions"><button data-np="resume" class="np-primary">Weiterreisen</button><button data-np="pause">Zur Pause</button></div>`;
  else if(overlay==='map'){
   const active=world!.room.region;
   body=`<span class="np-eyebrow">Alle Wege führen irgendwann nach Hause</span><h2>Die Nachtkarte</h2><p>${esc(world!.room.name)} · ${p.visited.length}/${rooms.length} Orte entdeckt</p>${active&&world!.room.id!=='final'?`<div class="np-map">${rooms.filter(r=>r.region===active&&r.index<16).map(r=>`<div class="${p.visited.includes(r.id)?'':'unseen'} ${p.cleared.includes(r.id)?'done':''} ${r.id===p.room?'current':''}">${p.visited.includes(r.id)?esc(r.name):'Unentdeckt'}<small>${r.kind==='boss'?'Hüter':r.kind==='tool'?'Werkzeug':['memory','timing','circuit'].includes(r.kind)?'Prüfung':r.kind==='camp'?'Station':''}</small></div>`).join('')}</div>`:''}<p class="np-muted">Schnellreise ist an Poststationen möglich. Innerhalb einer Region verbinden die vier Himmelsrichtungen benachbarte Kartenfelder. Für jeden Hüter braucht ihr die drei Prüfungsstempel.</p><div class="np-region-list"><button data-travel="home" ${world!.room.kind!=='camp'&&world!.room.id!=='final'?'disabled':''}>Sternhafen<small>Euer Zuhause</small></button>${regions.map(r=>`<button data-travel="${r.id}:0" ${world!.room.kind!=='camp'||!regionOpen(r.id,p.seals)?'disabled':''}>${p.seals.includes(r.id)?'✦ ':''}${r.name}<small>${regionOpen(r.id,p.seals)?r.subtitle:r.id<=3?'Nach dem Briefwald':r.id<=5?'Nach Uhrenviertel und Laternenmooren':'Nach Wolkenküche und Flüsterarchiv'}</small></button>`).join('')}${p.seals.length===6?`<button data-travel="final" ${world!.room.kind!=='camp'?'disabled':''}>Die Morgenmaschine<small>Das Finale</small></button>`:''}</div><div class="np-panel-actions"><button data-np="resume" class="np-primary">Weiterreisen</button><button data-np="journal">Aktuelles Ziel</button></div>`;
  }else if(overlay==='journal')body=`<span class="np-eyebrow">Notizen einer Nachtpostbotin</span><h2>Euer Reisebuch</h2><div class="np-journal"><h3>Was als Nächstes?</h3><p>${objective()}</p><details open><summary>Dieser Ort: ${esc(world!.room.name)}</summary><p>${esc(world!.room.hint)}</p>${world!.room.kind==='switches'?`<p>Die Stele nennt: ${world!.switchOrder.map(n=>['Blatt','Mond','Stern'][n]).join(' → ')}. Kristalle mit Nahkampf oder Fernwerkzeug treffen.</p>`:''}</details><details><summary>Kampf & Überleben</summary><p>Schläge treffen vor Mara. Orange Vorwarnungen zeigen, wohin Gegner angreifen werden. Rolle seitlich aus der Linie. Gepanzerte Wachen mit Haken betäuben oder nach ihrem Angriff treffen. Hüter blocken außerhalb ihrer Ruhephase. Das Werkzeug ihrer Region kann sie zusätzlich aus dem Takt bringen. In ihrer Ruhephase ist Zeit für mehrere Treffer. Ausdauer füllt sich von selbst. Heiltee gibt es an Poststationen.</p></details>${p.tools.map(t=>`<details><summary>${names[t]}</summary><p>${toolInfo[t]}</p></details>`).join('')}<h3>Die Geschichte bisher</h3><details><summary>Ein Brief von Morgen</summary>${opening.map(line=>`<p>${esc(line)}</p>`).join('')}</details>${regions.filter(r=>p.seals.includes(r.id)||p.cleared.includes(`${r.id}:13`)).map(r=>`<details><summary>${r.name}</summary><p>${esc(r.revelation)}</p>${p.seals.includes(r.id)?`<p>${esc(r.ending)}</p>`:''}</details>`).join('')}<h3>Aufträge</h3>${regions.map(r=>`<details><summary>${p.quests.includes(r.id)?'✓ ':''}${r.keeper}: ${r.quest}</summary><p>${p.quests.includes(r.id)?r.questEnd:`${p.letters.filter(id=>id.startsWith(r.id+':')).length}/3 gefunden. Sprich nach drei Briefen an der Poststation mit ${r.keeper}.`}</p></details>`).join('')}<h3>Gefundene Briefe · ${p.letters.length}</h3>${p.letters.map(id=>`<details><summary>${esc(roomById.get(id)?.name??id)}</summary><p>${esc(roomById.get(id)?.letter??'Ein Brief aus einer späteren Geschichte.')}</p></details>`).join('')||'<p>Noch keine Briefe. Achte auf die hellen Umschläge am Wegesrand.</p>'}</div><div class="np-panel-actions"><button data-np="resume" class="np-primary">Weiterreisen</button></div>`;
  else if(overlay==='dialogue')body=`<span class="np-eyebrow">${esc(dialogueTitle)}</span><p class="np-dialogue">${esc(dialogue[dialogueIndex])}</p><span class="np-dialogue-counter">${dialogueIndex+1} / ${dialogue.length}</span><div class="np-panel-actions"><button data-np="dialogue-next" class="np-primary">${dialogueIndex===dialogue.length-1?'Weiterreisen':'Weiterlesen'}</button></div>`;
  else if(overlay==='puzzle')body=puzzleView();
  else if(overlay==='ending')body=`<span class="np-eyebrow">Ein Brief an Morgen</span><h2>Es ist noch nicht zu spät.</h2><p>Nox legt den Schlüssel auf den Tisch. Die Morgenmaschine wartet auf eure Antwort.</p><div class="np-panel-actions"><button data-ending="together" class="np-primary">Nox die Hand reichen</button><button data-ending="release">Die Maschine abschalten</button></div><p class="np-muted">Beide Entscheidungen öffnen den Morgen. Eure Entscheidung verändert den Abschied, nicht den Wert eurer Reise.</p>`;
  panelBody.innerHTML=`<nav class="np-panel-nav"><button data-np="exit">← Logbuch</button>${overlay!=='title'&&overlay!=='conflict'&&overlay!=='pause'?'<button data-np="pause">Pause</button>':''}</nav>`+body;panel.scrollTop=0;
 }
 function objective(){if(!world)return '';const p=world.p;if(p.ending)return 'Der Morgen ist zurück. Offene Briefe, Aufträge und Geheimnisse warten weiter auf euch.';if(p.seals.length===6)return 'Kehrt zu einer Poststation zurück und reist über die Karte zur Morgenmaschine.';const r=regions.find(r=>regionOpen(r.id,p.seals)&&!p.seals.includes(r.id));return r?`Bringt das Morgenlicht aus „${r.name}“ zurück. Holt das Werkzeug, sammelt die drei Prüfungsstempel und besucht den Hüter. Die Karte zeigt euch die Pulte.`:'';}
 function startPuzzle(kind:RoomKind){const seed=seedNumber(world!.room.id);puzzle={kind,time:0,stage:0,hits:0,index:0,phase:kind==='memory'?'preview':'input',feedback:'',assist:world!.p.difficulty==='cozy',sequence:sequence(seed,3+Math.floor(world!.room.region/2)),circuit:kind==='circuit'?circuit(world!.room.region<=2?3:world!.room.region===6?5:4,seed):null,lastVisual:-99};openPanel('puzzle');}
 function puzzleView(){if(!puzzle||!world)return '';const q=puzzle;const common=`<div class="np-panel-actions"><button data-np="puzzle-help">${q.kind==='circuit'?'Ein Teil richtig drehen':q.kind==='memory'?'Folge erneut zeigen':'Größere Trefferzone'}</button><button data-np="puzzle-cancel">Zurück in die Welt</button></div>`;
  if(q.kind==='memory')return `<span class="np-eyebrow">Prüfung der Erinnerung</span><h2>Das Sternenecho</h2><p>Merke dir die leuchtenden Zeichen und tippe sie danach in derselben Reihenfolge. Drei Folgen öffnen den Stempel. Du kannst jede Folge erneut ansehen. ${world.room.region>=3?'Achtung: Die zweite Folge beantwortet ihr rückwärts.':''}</p><p class="np-puzzle-status" role="status">${q.feedback||`Folge ${q.stage+1}/3${world.room.region>=3&&q.stage===1?' · RÜCKWÄRTS':''} · ${q.phase==='preview'?'Schau genau hin.':`${q.index}/${q.sequence.length} Zeichen`}`}</p><div class="np-memory">${symbols.map((s,i)=>`<button data-memory="${i}" aria-label="${['Stern','Mond','Blatt','Raute'][i]}" ${q.phase!=='input'?'disabled':''}>${s}</button>`).join('')}</div>${common}`;
  if(q.kind==='circuit'){const b=q.circuit!,lit=connected(b);return `<span class="np-eyebrow">Prüfung der Verbindung</span><h2>Ein Licht findet seinen Weg.</h2><p>Drehe die Leitungen durch Antippen. Verbinde den Eingang links oben mit dem Ausgang an Feld ${b.end+1} (${({1:'oben',2:'rechts',4:'unten',8:'links'} as Record<number,string>)[b.exit]}). Alle ${b.tiles.length} Felder müssen vom Eingang aus leuchten.</p><div class="np-puzzle-grid" style="grid-template-columns:repeat(${b.size},1fr)">${b.tiles.map((mask,i)=>`<button data-pipe="${i}" aria-label="Leitung ${i+1} drehen${i===b.end?' · Ausgang '+({1:'oben',2:'rechts',4:'unten',8:'links'} as Record<number,string>)[b.exit]:''}"><svg viewBox="0 0 64 64"><rect width="64" height="64" rx="8" fill="${lit.has(i)?'#46695f':'#273b49'}"/><g stroke="${lit.has(i)?'#efd091':'#a4bbb8'}" stroke-width="7" stroke-linecap="round">${[[1,32,0],[2,64,32],[4,32,64],[8,0,32]].filter(([bit])=>mask&bit).map(([,x,y])=>`<path d="M32 32L${x} ${y}"/>`).join('')}</g><circle cx="32" cy="32" r="5" fill="#f0d496"/>${i===0||i===b.end?`<text x="32" y="57" text-anchor="middle" font-size="10" fill="#fff6d7">${i===0?'EIN':'AUS'}</text>`:''}</svg></button>`).join('')}</div><p class="np-muted">${lit.size}/${b.tiles.length} Felder leuchten · ${b.moves} Drehungen</p>${common}`;}
  return `<span class="np-eyebrow">Prüfung der ruhigen Hand</span><h2>Express nach Morgen</h2><p>Tippe, wenn der Strich die helle Mitte erreicht. Ein Tipp pro Paket. Sechs von acht Paketen müssen ankommen.${world.room.region>=4?' Rücksendungen lässt du ohne Tipp vorbeiziehen.':''}</p><p class="np-puzzle-status" role="status">${world.room.region>=4&&[2,5].includes(q.stage)?'RÜCKSENDUNG · NICHT TIPPEN · ':''}Paket ${Math.min(8,q.stage+1)}/8 · ${q.hits} zugestellt${q.feedback?' · '+q.feedback:''}</p><div class="np-timing"><span class="np-timing-zone" style="left:${q.assist?30:40}%;width:${q.assist?40:20}%"></span><span class="np-timing-marker" style="left:0"></span></div><button data-np="sort" class="np-primary" style="width:100%;min-height:70px" ${q.phase!=='input'?'disabled':''}>Jetzt zustellen</button>${common}`;
 }
 function puzzleSuccess(){completeRoom(world!);puzzle=null;talk('Stempel erteilt',['Pipp betrachtet den Stempel. „Amtlich bestätigt: Ihr könnt Dinge. Wir wussten das natürlich vorher.“','Der Weg zum Hüter öffnet sich, sobald alle drei Prüfungen dieser Region geschafft sind.']);checkpoint();}
 function updatePuzzle(dt:number){if(!puzzle||!world)return;const q=puzzle;q.time+=dt;
  if(q.kind==='memory'&&q.phase==='preview'){
   const i=Math.floor(q.time/.85)-1,on=q.time%.85<.58,visual=i*2+Number(on);if(visual!==q.lastVisual){q.lastVisual=visual;container.querySelectorAll('[data-memory]').forEach(b=>b.classList.toggle('lit',on&&i>=0&&i<q.sequence.length&&Number((b as HTMLElement).dataset.memory)===q.sequence[i]));if(on&&i>=0&&i<q.sequence.length)audio.effect('bell');}
   if(i>=q.sequence.length){q.phase='input';q.time=0;q.index=0;q.feedback=world.room.region>=3&&q.stage===1?'Jetzt rückwärts antworten.':'Jetzt ihr.';renderPanel();}
  }else if(q.kind==='memory'&&q.phase==='feedback'&&q.time>1.2){q.phase='preview';q.time=0;q.lastVisual=-99;renderPanel();}
  else if(q.kind==='timing'){
   if(q.phase==='input'){const position=timingPosition(q.time,q.stage);const marker=container.querySelector<HTMLElement>('.np-timing-marker');if(marker)marker.style.left=`${position*100}%`;if(position>=1)sort(false);}
   else if(q.time>.65){q.stage++;q.time=0;q.phase='input';q.feedback='';if(q.stage>=8){if(q.hits>=6){puzzleSuccess();return;}q.stage=0;q.hits=0;q.feedback='Noch einmal. Sechs Pakete reichen – ihr könnt die Trefferzone vergrößern.';}renderPanel();}
  }
 }
 function sort(tapped:boolean){if(!puzzle||puzzle.phase!=='input')return;const q=puzzle,returnMail=world!.room.region>=4&&[2,5].includes(q.stage),hit=returnMail?!tapped:tapped&&Math.abs(timingPosition(q.time,q.stage)-.5)<=(q.assist?.2:.1);q.hits+=Number(hit);q.feedback=hit?(returnMail?'Richtig zurückgeschickt!':'Zugestellt!'):'Daneben. Das nächste kommt.';q.phase='feedback';q.time=0;audio.effect(hit?'bell':'swing');renderPanel();}
 function handleEvents(){if(!world)return;const events=world.events.splice(0);for(const event of events){if(event.type==='text'&&event.text)notify(event.text);else if(event.type==='sound')audio.effect(event.kind??'');else if(event.type==='changed')checkpoint();else if(event.type==='death'){talk('Kurz im Sternenstaub gelegen',['Pipp zählt zur Sicherheit eure Finger. „Alle da. Ausgezeichnet. Noch einmal?“','Ihr beginnt am Eingang dieses Raums. Briefe, Werkzeuge und abgeschlossene Prüfungen bleiben erhalten. In der Pause könnt ihr die Schwierigkeit auf „Gemütlich“ stellen.']);}
   else if(event.type==='puzzle')startPuzzle(event.kind as RoomKind);
   else if(event.type==='ending'){if(world.p.ending)talk('Ein Morgen später',[world.p.ending==='together'?'Nox und Lio sitzen am Meer. Vor ihnen stehen zwei Tassen. Keine Uhr.':'Die Morgenmaschine steht still. An ihrer Stelle wächst ein Garten. Nox hat eine Fahrkarte ans Meer gekauft.','Mara öffnet die Tasche. Ein neuer Brief: „Danke. Bis morgen.“ Pipp nickt. „Das klingt nach einem sehr guten Plan.“']);else talk('Nox, Nachtwächter',finale,()=>{overlay='ending';renderPanel();});}
   else if(event.type==='dialogue'){
    const r=regions[world.room.region-1];if(event.kind==='camp'){
     if(!r)talk('Pipp · Sternhafen',world.p.ending?['„Guten Morgen!“, sagt Pipp. Er probiert den Satz noch dreimal. Er klingt jedes Mal gut.','Die Welt ist wieder unterwegs. Ihr dürft offene Briefe zustellen, Geheimnisse suchen oder einfach ein bisschen durchatmen.']:world.p.intro?['„Gute Nachrichten“, sagt Pipp. „Die Welt ist noch da. Schlechte Nachrichten: Das Amt auch.“',objective(),'An Poststationen könnt ihr über die Karte reisen. Die Spielstube ist in der Pause erreichbar. Euer altes Babyabenteuer bleibt dort erhalten.']:opening);
     else {const count=world.p.letters.filter(id=>id.startsWith(r.id+':')).length;if(count>=3&&!world.p.quests.includes(r.id)){world.p.quests.push(r.id);world.p.sparks+=3;checkpoint();talk(r.keeper,[r.questEnd,'Drei Sternenfunken für eure Zustellungen. Manchmal ist ein Umweg genau der richtige Weg.']);}else talk(r.keeper,world.p.seals.includes(r.id)?[r.ending,`${r.quest} (${count}/3)`,world.p.quests.includes(r.id)?r.questEnd:'Wenn ihr drei Briefe gefunden habt, bringt sie zu mir.']:[...r.intro,`${r.quest} (${count}/3)`]);}
    }else if(event.kind==='tool')talk(r.toolName,[`In der Truhe liegt: ${r.toolName}. Pipp ist beeindruckt. Er hätte einen Keks genommen.`,toolInfo[r.tool],'Werkzeuge wählt ihr im Pausenmenü aus. Taste L oder die Werkzeugtaste benutzt das gewählte Werkzeug.']);
    else if(event.kind==='letter')talk('Ein gefundener Brief',[world.room.letter!,'Der Brief ist jetzt im Reisebuch. Ein Sternenfunke bleibt bei euch.']);
    else if(event.kind==='story')talk('Was die Nacht verschweigt',[r.revelation]);
    else if(event.kind==='boss')talk(r.boss,[r.ending,r.revelation,`Das ${world.p.seals.length}. Morgenlicht gehört wieder zum Himmel. Neue Wege sind über die Nachtkarte an einer Poststation erreichbar.`]);
    else if(event.kind==='switches')talk('Die Stele',[`„Zuerst ${['Blatt','Mond','Stern'][world.switchOrder[0]]}, dann ${['Blatt','Mond','Stern'][world.switchOrder[1]]}, zuletzt ${['Blatt','Mond','Stern'][world.switchOrder[2]]}.“`,`Die Kristalle stehen oben im Raum. Schlage sie in dieser Reihenfolge oder triff sie mit einem Fernwerkzeug.`]);
   }
  }}
 function hud(){if(!world)return;const p=world.p;container.querySelector('.np-hearts')!.textContent='♥'.repeat(Math.max(0,p.hp))+'♡'.repeat(Math.max(0,maxHp(p)-p.hp));container.querySelector('.np-hearts')!.setAttribute('aria-label',`${p.hp} von ${maxHp(p)} Herzen`);(container.querySelector('.np-meter span') as HTMLElement).style.width=`${world.stamina}%`;container.querySelector('.np-location')!.textContent=world.room.name;container.querySelector('.np-tool-button')!.innerHTML=`${p.tools.includes(p.equipped)?({bell:'Glocke',hook:'Haken',lantern:'Laterne',gust:'Wind',echo:'Feder',clock:'Zeit'})[p.equipped]:'Werkzeug'}<small>L</small>`;const quick=container.querySelector<HTMLButtonElement>('.np-quicktool')!;quick.hidden=p.tools.length<2;quick.textContent=names[p.equipped]+' ↻';const boss=world.enemies.find(e=>e.type==='boss'),bar=container.querySelector<HTMLElement>('.np-bossbar')!;bar.hidden=!boss;if(boss)bar.innerHTML=`${esc(regions[world.room.region-1].boss)}<div><span style="width:${boss.hp/boss.maxHp*100}%"></span></div>`;if(world.time>toastUntil)container.querySelector<HTMLElement>('.np-toast')!.hidden=true;}
 function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);if(hidden||document.visibilityState==='hidden'){last=now;return;}const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(!world)return;
  if(!overlay){const x=stick.x+Number(keys.has('arrowright')||keys.has('d'))-Number(keys.has('arrowleft')||keys.has('a')),y=stick.y+Number(keys.has('arrowdown')||keys.has('s'))-Number(keys.has('arrowup')||keys.has('w'));step(world,{x,y,attack:held.attack||keys.has('j')||keys.has(' '),roll:held.roll||keys.has('k'),tool:held.tool||keys.has('l'),interact:interaction},dt);interaction=false;handleEvents();saveTime+=dt;if(saveTime>=20){saveTime=0;checkpoint();}}
  else if(overlay==='puzzle'){world.p.playSeconds+=dt;updatePuzzle(dt);}
  else if(overlay==='dialogue'||overlay==='ending')world.p.playSeconds+=dt;
  drawWorld(ctx,world,reduced);if(now-lastHud>100){hud();lastHud=now;}
 }
 async function load(){loadError='';try{const p=await storage.load();if(disposed)return;world=createWorld(p);loaded=true;if(storage.conflict)overlay='conflict';else if(storage.dirty)checkpoint();}catch(e){loadError=e instanceof Error?e.message:'Abenteuerdatenbank nicht erreichbar. Bitte Einrichtung und Verbindung prüfen.';}if(!disposed){renderPanel();updateSaveStatus();}}
 const click=async(event:MouseEvent)=>{
  const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button||button.disabled)return;
  const action=button.dataset.np,p=world?.p;
  if(action==='exit'){pause();onExit();return;}if(action==='arcade'){pause();onArcade();return;}if(action==='reload'){await load();return;}if(!world||!p)return;
  if(button.dataset.travel){const target=button.dataset.travel;if(world.room.kind!=='camp'&&world.room.id!=='final')return;const room=roomById.get(target);if(!room||(!['home','final'].includes(target)&&!regionOpen(room.region,p.seals))||(target==='final'&&p.seals.length!==6))return;enter(world,target);overlay=null;renderPanel();audio.region(world.room.region);handleEvents();checkpoint();return;}
  if(button.dataset.skill){if(buySkill(p,button.dataset.skill)){checkpoint();audio.effect('success');}renderPanel();return;}
  if(button.dataset.equip){const tool=button.dataset.equip as Tool;if(p.tools.includes(tool)){p.equipped=tool;checkpoint();renderPanel();}return;}
  if(button.dataset.ending){p.ending=button.dataset.ending as Save['ending'];checkpoint();talk('Der erste Morgen',p.ending==='together'?['Mara reicht Nox die Hand. Zum ersten Mal seit Jahren hat er nichts zu bewachen. Nur einen Weg vor sich.','Der Himmel wird hell. Im Briefwald antwortet jemand. Im Uhrenviertel verpasst Oskar einen Termin. In der Wolkenküche brennt ein Toast an. Es ist ein ganz gewöhnlicher, wundervoller Morgen.','Am Meer wartet Lio. Sie rückt einen Stuhl zurecht. Nox setzt sich. „Achtzehn“, sagt er und zeigt auf einen verblassenden Stern.','Danke, dass ihr den Morgen abgeholt habt. Ihr könnt offene Briefe und Aufträge weiter entdecken.']:['Mara dreht den Schlüssel. Die Maschine wird leise. Dann still. Nicht die ganze Welt – nur diese eine Maschine.','Nox öffnet das Fenster. Unten streitet jemand mit einem Fahrrad. Jemand lacht. Irgendwo wird Kaffee gekocht. Keine dieser Sachen ist perfekt.','„Ich glaube, ich muss ans Meer“, sagt Nox. Pipp reicht ihm den Brief. „Die Adresse steht drauf.“','Danke, dass ihr den Morgen abgeholt habt. Ihr könnt offene Briefe und Aufträge weiter entdecken.']);return;}
  if(button.dataset.memory!==undefined&&puzzle?.phase==='input'){
   const q=puzzle,n=Number(button.dataset.memory);if(n===q.sequence[world.room.region>=3&&q.stage===1?q.sequence.length-1-q.index:q.index]){q.index++;audio.effect('bell');if(q.index===q.sequence.length){q.stage++;if(q.stage===3){puzzleSuccess();return;}q.sequence=sequence(seedNumber(world.room.id)+q.stage,(q.assist?3:3+Math.floor(world.room.region/2))+q.stage);q.phase='preview';q.time=0;q.index=0;q.lastVisual=-99;q.feedback='Gut gemerkt. Die nächste Folge kommt.';}}else{q.phase='feedback';q.time=0;q.index=0;q.feedback='Fast. Schau die Folge noch einmal an.';}renderPanel();return;
  }
  if(button.dataset.pipe!==undefined&&puzzle?.circuit){const c=puzzle.circuit,i=Number(button.dataset.pipe);c.tiles[i]=rotate(c.tiles[i]);c.moves++;audio.effect('bell');if(circuitSolved(c))puzzleSuccess();else renderPanel();return;}
  switch(action){
   case 'start':if(!p.intro){p.intro=true;talk('Ein Brief von Morgen',opening,()=>{overlay=null;renderPanel();notify('Geh mit dem Steuerkreis oder WASD zu Pipp in der Mitte. E spricht ihn an. Die Karte öffnet den Weg zum Briefwald.');});checkpoint();}else{overlay=null;renderPanel();}void audio.start(p.sound,world.room.region);break;
   case 'pause':pause();break;case 'resume':resume();break;
   case 'map':openPanel('map');break;case 'skills':openPanel('skills');break;case 'journal':openPanel('journal');break;
   case 'interact':if(!overlay){interact(world);handleEvents();}break;
   case 'retreat':enter(world,world.room.region?`${world.room.region}:0`:'home');overlay=null;renderPanel();handleEvents();checkpoint();break;
   case 'cycle':if(p.tools.length){p.equipped=p.tools[(p.tools.indexOf(p.equipped)+1)%p.tools.length];notify(names[p.equipped]+': '+toolInfo[p.equipped]);checkpoint();}break;
   case 'sound':p.sound=!p.sound;void audio.start(p.sound,world.room.region);checkpoint();renderPanel();break;
   case 'difficulty':p.difficulty=p.difficulty==='normal'?'cozy':'normal';checkpoint();renderPanel();break;
   case 'tea':if(p.tea>0&&p.hp<maxHp(p)){p.tea--;p.hp=Math.min(maxHp(p),p.hp+4);checkpoint();}renderPanel();break;
   case 'save':checkpoint();await storage.flush();renderPanel();break;
   case 'export':case 'export-conflict':{let output=p;if(action==='export-conflict'){const backup=storage.lastConflict();if(!backup){notify('Es gibt keine archivierte Konfliktsicherung.');break;}output=backup;}const blob=new Blob([JSON.stringify(output,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nachtpost-spielstand.json';a.click();URL.revokeObjectURL(url);break;}
   case 'remote':try{const remote=await storage.useRemote();world=createWorld(remote);overlay='title';renderPanel();}catch(e){notify(e instanceof Error?e.message:'Laden fehlgeschlagen.');}break;
   case 'dialogue-next':dialogueIndex++;if(dialogueIndex>=dialogue.length){const cb=afterDialogue;afterDialogue=null;overlay=null;renderPanel();cb?.();}else renderPanel();break;
   case 'sort':sort(true);break;
   case 'puzzle-help':if(puzzle){puzzle.assist=true;if(puzzle.circuit){circuitHint(puzzle.circuit);if(circuitSolved(puzzle.circuit)){puzzleSuccess();break;}}else if(puzzle.kind==='memory'){puzzle.phase='preview';puzzle.index=0;puzzle.time=0;puzzle.lastVisual=-99;puzzle.feedback='Noch einmal in Ruhe.';}renderPanel();}break;
   case 'puzzle-cancel':puzzle=null;overlay=null;renderPanel();break;
  }
 };
 container.addEventListener('click',click);
 function stickMove(event:PointerEvent){if(event.pointerId!==pointer)return;const rect=stickEl.getBoundingClientRect(),radius=rect.width*.36,x=event.clientX-rect.left-rect.width/2,y=event.clientY-rect.top-rect.height/2,len=Math.max(radius,Math.hypot(x,y));stick={x:x/len,y:y/len};knob.style.transform=`translate(${stick.x*radius}px,${stick.y*radius}px)`;}
 const stickDown=(e:PointerEvent)=>{if(overlay||hidden)return;e.preventDefault();pointer=e.pointerId;stickEl.setPointerCapture(e.pointerId);stickMove(e);};
 const stickUp=(e:PointerEvent)=>{if(e.pointerId===pointer){pointer=null;stick={x:0,y:0};knob.style.transform='';}};
 stickEl.addEventListener('pointerdown',stickDown);stickEl.addEventListener('pointermove',stickMove);stickEl.addEventListener('pointerup',stickUp);stickEl.addEventListener('pointercancel',stickUp);stickEl.addEventListener('lostpointercapture',stickUp);
 container.querySelectorAll<HTMLButtonElement>('[data-hold]').forEach(b=>{const action=b.dataset.hold as keyof typeof held;b.addEventListener('pointerdown',e=>{if(overlay||hidden)return;e.preventDefault();b.setPointerCapture(e.pointerId);held[action]=true;});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{held[action]=false;});});
 const keyDown=(e:KeyboardEvent)=>{if(hidden||!world)return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d','j','k','l','e','escape','m','i'].includes(key))e.preventDefault();if(e.repeat&&['e','escape','m','i'].includes(key))return;if(key==='escape'){if(overlay==='pause')resume();else if(overlay!=='title')pause();return;}if(overlay)return;if(key==='m'){openPanel('map');return;}if(key==='i'){openPanel('journal');return;}if(key==='e')interaction=true;else keys.add(key);};
 const keyUp=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());
 const visibility=()=>{if(document.visibilityState==='hidden')pause();};
 const beforeUnload=(e:BeforeUnloadEvent)=>{if(storage.pending||storage.dirty){e.preventDefault();e.returnValue='';}};
 document.addEventListener('keydown',keyDown);document.addEventListener('keyup',keyUp);document.addEventListener('visibilitychange',visibility);window.addEventListener('beforeunload',beforeUnload);
 renderPanel();void load();last=performance.now();frame=requestAnimationFrame(animate);
 return {show(){hidden=false;container.hidden=false;last=performance.now();renderPanel();},pause,hide(){pause();hidden=true;container.hidden=true;audio.pause();},dispose(){checkpoint();disposed=true;storage.disposed=true;resize.disconnect();cancelAnimationFrame(frame);audio.dispose();document.removeEventListener('keydown',keyDown);document.removeEventListener('keyup',keyUp);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('beforeunload',beforeUnload);container.removeEventListener('click',click);container.replaceChildren();}};
}
